name: Check PR
on: [pull_request]

jobs:
  pr:
    name: PR check
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Run unit tests
        shell: bash
        run: ./gradlew --continue :lib:testReleaseUnitTest :example:testReleaseUnitTest
      - name: Run build
        shell: bash
        run: ./gradlew assembleDebug

